CREATE DATABASE BindPlanet
USE BindPlanet

CREATE TABLE AUTOR (
	ID_AUTOR INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(MAX) NOT NULL,
	PRIMARY KEY(ID_AUTOR)
);

CREATE TABLE EDITORA (
	ID_EDITORA INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(MAX) NOT NULL,
	PRIMARY KEY(ID_EDITORA)
);

CREATE TABLE GENERO (
	ID_GENERO INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(MAX) NOT NULL,
	PRIMARY KEY(ID_GENERO)
);

CREATE TABLE TITULO (
	ID_TITULO INT NOT NULL IDENTITY(1,1),
	TITULO VARCHAR(MAX) NOT NULL,
	DTA_COMPRA DATE NOT NULL,
	PRECO MONEY NOT NULL,
	ID_EDITORA INT NOT NULL, 
	ID_GENERO INT NOT NULL,
	ID_AUTOR INT NOT NULL,
	PRIMARY KEY(ID_TITULO),
	FOREIGN KEY (ID_EDITORA) REFERENCES EDITORA(ID_EDITORA),
	FOREIGN KEY (ID_GENERO) REFERENCES GENERO(ID_GENERO),
	FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID_AUTOR)
);

CREATE TABLE MUSICA (
	ID_MUSICA INT NOT NULL IDENTITY(1,1),
	NOME VARCHAR(MAX) NOT NULL,
	ID_AUTOR INT NOT NULL,
	ID_TITULO INT NOT NULL,
	PRIMARY KEY(ID_MUSICA),
	FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID_AUTOR),
	FOREIGN KEY (ID_TITULO) REFERENCES TITULO(ID_TITULO)
);

SELECT COUNT(*) FROM TITULO


SELECT COUNT(*) 
FROM AUTOR A,TITULO T 
WHERE A.ID_AUTOR=T.ID_AUTOR AND A.NOME='Joel Pinto'


SELECT A.NOME 
FROM AUTOR A,TITULO T 
WHERE A.ID_AUTOR=T.ID_AUTOR AND convert(varchar(10), T.DTA_COMPRA, 102) = convert(varchar(10), '2010.02.01', 102)  and T.PRECO=12


SELECT DISTINCT A.NOME	
FROM AUTOR A,TITULO T 
WHERE A.ID_AUTOR=T.ID_AUTOR 
	AND convert(varchar(10), T.DTA_COMPRA, 102) = convert(varchar(10), '1970.04.04', 102) 
	and T.PRECO=20



SELECT TOP 1 E.NOME ,COUNT(*) AS NUM  
FROM EDITORA E ,GENERO G, TITULO T
WHERE G.NOME='Heavy Metal' AND G.ID_GENERO=T.ID_TITULO AND E.ID_EDITORA=T.ID_TITULO
GROUP BY E.NOME
ORDER BY NUM
